project:
  type: website

website:
  title: "SPD's Brinner and Learn Series"
  sidebar:
    style: "docked"
    search: true
    tools:
      - icon: github
        href: https://github.com/rmi/brinner_and_learn
    contents:
      - index.qmd
      - file: slides/2025-01-31_tdd_presentation.qmd
        target: test_driven_development
      - file: slides/2025-02-11_pr_practices.qmd
        target: pull_requests
      - file: slides/2025-03-11_tickets.qmd
        target: tickets
      - file: slides/2025-04-08_data_pipeline_manifest.qmd
        target: data_pipeline_manifest
      - file: slides/2025-10-21_text_encoding.qmd
        target: text_encoding
      - file: slides/2025-11-04_okrs.qmd
        target: okrs
      - file: slides/2026-01-13_conventional_commits.qmd
        target: conventional_commits

format:
  html:
    theme:
      dark: darkly
      light: flatly
    css: styles.css
    toc: false
    link-external-newwindow: true
